import {test,expect} from '@playwright/test';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import {adminAuth,author,service,db,password,key,headSha,baseSha} from './fixtures.js';
test('Browser + SDK emulator journey: create → refresh → contract approval → claim/context/submit → human review',async({page})=>{
 const browserTitle='Browser read-back acceptance '+key();
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const login=async(email:string)=>{await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Roadmap',exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Project',exact:true}).selectOption({label:'Customer Portal'});await expect(page.locator('[data-plane-component=BaseGanttLayout]')).toBeVisible();};
 await page.goto('/');await login('author@example.test');await expect(page.locator('[data-plane-component=BaseGanttLayout]')).toBeVisible();await page.getByLabel('Zoom',{exact:true}).selectOption('week');await expect(page.getByLabel('Zoom',{exact:true})).toHaveValue('week');await page.getByLabel('Zoom',{exact:true}).selectOption('quarter');await expect(page.getByLabel('Zoom',{exact:true})).toHaveValue('quarter');await page.getByRole('button',{name:/^Open HWS-1:/}).click();await expect(page.getByLabel('Zoom',{exact:true})).toHaveValue('quarter');await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByText('Data refreshed',{exact:true})).toBeVisible();await expect(page.getByLabel('Zoom',{exact:true})).toHaveValue('quarter');await page.getByRole('button',{name:'Close details'}).click();await page.getByLabel('Zoom',{exact:true}).selectOption('month');await page.screenshot({path:'docs/evidence/roadmap-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Work',exact:true}).click();await page.getByRole('button',{name:'Create work item',exact:true}).click();
 const modal=page.getByRole('dialog');await expect(modal).toBeVisible();await modal.getByLabel('Title',{exact:true}).fill(browserTitle);await modal.getByLabel('Description',{exact:true}).fill('Verify the complete persisted handoff and independent human acceptance.');await modal.getByLabel('Acceptance criteria',{exact:true}).fill('Saved work survives browser refresh');await modal.getByRole('button',{name:'Create work item',exact:true}).click();await expect(modal).not.toBeVisible();
 const readback=page.waitForResponse(response=>response.url().endsWith('/us-central1/api')&&response.request().postDataJSON()?.operation==='get_project_status'&&response.ok());await page.reload();await readback;await expect(page.getByRole('heading',{name:browserTitle,exact:true})).toBeVisible();
 await page.getByRole('tab',{name:'Contract',exact:true}).click();await page.getByLabel('Implementation scope').fill('Verify persistence and review on the synthetic project');await page.getByLabel('Portal implementation specification',{exact:true}).check();await page.getByRole('button',{name:'Publish new contract',exact:true}).click();await expect(page.getByText('New contract published for approval',{exact:true})).toBeVisible();
 const taskId=new URL(page.url()).searchParams.get('task')!;
 await page.getByRole('button',{name:'Knowledge',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Private unsaved title');await page.getByLabel('Document content',{exact:true}).fill('Private unsaved body');await page.getByRole('button',{name:'Sign out',exact:true}).click();await login('reviewer@example.test');await page.getByRole('button',{name:'Knowledge',exact:true}).click();await expect(page.getByLabel('Title',{exact:true})).toHaveValue('');await expect(page.getByLabel('Document content',{exact:true})).toHaveValue('');
 await page.getByRole('button',{name:'Work',exact:true}).click();await page.getByRole('button',{name:new RegExp(browserTitle)}).click();await page.getByRole('tab',{name:'Contract',exact:true}).click();await page.getByRole('button',{name:'Approve pinned contract',exact:true}).click();await expect(page.getByText('Contract approved',{exact:true})).toBeVisible();
 const u=await adminAuth.getUserByEmail('author@example.test');const projects=await service.execute(author(u.uid),'list_projects',{});const p=projects.projects.find((p:Record<string,unknown>)=>p.name==='Customer Portal');const base={workspaceId:p.workspaceId,projectId:p.projectId};
 const g=await service.execute(author(u.uid),'grant_connection',{...base,write:true,consent:true,label:'Browser-associated SDK harness',requestKey:key()});
 const client=new Client({name:'browser-associated-sdk-harness',version:'0.1.0'});await client.connect(new StreamableHTTPClientTransport(new URL('http://127.0.0.1:15001/demo-hunpeolabs-workspace/us-central1/mcp'),{requestInit:{headers:{Authorization:`Bearer ${g.secret}`}}}));
 const call=async(name:string,input:Record<string,unknown>)=>{const r=await client.callTool({name,arguments:input});expect(r.isError).toBeUndefined();return r.structuredContent as Record<string,any>;};
 try{
  const r=await call('recommend_work',base),t=r.suggested.find((t:Record<string,unknown>)=>t.taskId===taskId);expect(t).toBeTruthy();
  const c=(await call('claim_work',{...base,taskId,expectedVersion:t.expectedWorkVersion,contractHash:t.contractHash,requestKey:key()})).claim;
  const manifest=(await call('get_work_context',{...base,taskId,executionId:c.executionId})).manifest;for(const part of manifest.parts)await call('read_context_part',{...base,taskId,executionId:c.executionId,partId:part.id});
  const cp=await call('checkpoint_work',{...base,taskId,executionId:c.executionId,generation:c.generation,expectedVersion:1,requestKey:key(),state:'started',summary:'Browser saved and refreshed work. SDK read exact contract context.',baseSha,headSha,nextAction:'Request human review',tests:[{command:'Browser read-back assertion',result:'PASS'}]});
  await call('submit_delivery',{...base,taskId,executionId:c.executionId,generation:c.generation,expectedVersion:cp.claim.version,requestKey:key(),headSha,baseSha,pr:null,acEvidence:[{acId:'AC-1',result:'PASS',command:'Browser refresh read-back'}],limitations:'Synthetic SHA, SDK harness, no provider verification.'});
 }finally{await client.close();}
 await page.getByRole('button',{name:'Close details'}).click();await page.getByRole('button',{name:'Reviews',exact:true}).click();await page.getByRole('button',{name:'Refresh',exact:true}).click();
 const review=page.locator('.review-row').filter({hasText:browserTitle});await expect(review).toBeVisible();await review.getByLabel('Review decision').selectOption('accept');await review.getByLabel('Review reason').fill('Independently observed saved work after refresh. Synthetic pilot acceptance only.');await review.getByRole('button',{name:'Record human review'}).click();await expect(page.getByText('Review decision recorded',{exact:true})).toBeVisible();await expect(review.getByText('Accepted',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Roadmap',exact:true}).click();await page.screenshot({path:'docs/evidence/roadmap-accepted.png',fullPage:true});
 await page.setViewportSize({width:768,height:1024});await page.screenshot({path:'docs/evidence/roadmap-tablet.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/evidence/roadmap-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const projectBox=await page.locator('.project-select').boundingBox(),navBox=await page.getByRole('navigation',{name:'Project navigation'}).boundingBox();expect(projectBox!.y+projectBox!.height).toBeLessThanOrEqual(navBox!.y);await expect.poll(()=>page.evaluate(()=>{const bar=document.querySelector('.plan-bar')?.getBoundingClientRect(),timeline=document.querySelector('.roadmap-scroll')?.getBoundingClientRect();return !!bar&&!!timeline&&bar.right>timeline.left&&bar.left<timeline.right;})).toBe(true);
 await page.getByRole('button',{name:'Work',exact:true}).click();await page.getByRole('button',{name:'Create work item',exact:true}).click();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();
 expect(errors).toEqual([]);
});

test('Editor ignores delayed response after choosing New document',async({page})=>{
 await page.goto('/');await page.getByLabel('Email',{exact:true}).fill('author@example.test');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Roadmap',exact:true})).toBeVisible();
 await page.getByRole('combobox',{name:'Project',exact:true}).selectOption({label:'Customer Portal'});await expect(page.locator('[data-plane-component=BaseGanttLayout]')).toBeVisible();await page.getByRole('button',{name:'Knowledge',exact:true}).click();
 let release!:()=>void,arrived!:()=>void;const barrier=new Promise<void>(r=>release=r),started=new Promise<void>(r=>arrived=r);
 await page.route('**/us-central1/api',async route=>{const input=route.request().postDataJSON();if(input.operation==='get_document_revision'){const response=await route.fetch();arrived();await barrier;await route.fulfill({response});}else await route.continue();});
 await page.getByRole('button',{name:/Portal implementation specification/}).click();await started;
 await page.getByRole('button',{name:'New document',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Fresh unsaved draft');await page.getByLabel('Document content',{exact:true}).fill('Fresh content');
 release();await expect(page.getByText('Document loaded',{exact:true})).toBeVisible();await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Fresh unsaved draft');await expect(page.getByLabel('Document content',{exact:true})).toHaveValue('Fresh content');
});

async function loginAsk(page:import('@playwright/test').Page,email='author@example.test'){
 await page.goto('/');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.locator('[data-ask-workspace]')).toBeVisible();
}
const askBox=(page:import('@playwright/test').Page)=>page.getByRole('textbox',{name:'Ask Workspace',exact:true});
const askDialog=(page:import('@playwright/test').Page)=>page.getByRole('dialog',{name:'HunpeoLabs',exact:true});
const settlePanel=async(page:import('@playwright/test').Page)=>expect.poll(()=>askDialog(page).evaluate(e=>e.getAnimations().every(a=>a.playState!=='running'))).toBe(true);

test('Actual Workspace Ask: source layout, motion, help navigation, privacy, modal coexistence and mobile',async({page,context})=>{
 const unexpected:string[]=[];page.on('request',r=>{const u=new URL(r.url());if(['http:','https:'].includes(u.protocol)&&!['localhost','127.0.0.1'].includes(u.hostname))unexpected.push(u.origin);});
 await loginAsk(page);const reference=await context.newPage();await reference.route('**/*',route=>{const url=new URL(route.request().url());return url.hostname==='127.0.0.1'&&url.port==='15174'?route.continue():route.abort();});
 await reference.goto('http://127.0.0.1:15174/');await expect(reference.getByRole('textbox',{name:'Ask HunpeoLabs'})).toBeVisible();
 const shape=async(p:import('@playwright/test').Page,label:string)=>p.getByRole('textbox',{name:label,exact:true}).evaluate(e=>{const form=e.closest('form')!,r=form.getBoundingClientRect(),c=getComputedStyle(form);return {width:r.width,height:r.height,border:c.borderColor,radius:c.borderRadius,background:c.backgroundColor};});
 for(const size of [{width:1440,height:1000},{width:768,height:1024},{width:390,height:844}]){
  await page.setViewportSize(size);await reference.setViewportSize(size);expect(await shape(page,'Ask Workspace')).toEqual(await shape(reference,'Ask HunpeoLabs'));
  await page.screenshot({path:`docs/evidence/ask-idle-${size.width}.png`,fullPage:true});await reference.screenshot({path:`docs/evidence/ask-source-idle-${size.width}.png`,fullPage:true});
 }
 await page.setViewportSize({width:1440,height:1000});await reference.setViewportSize({width:1440,height:1000});
 await askBox(page).fill('How do I read the roadmap?');await page.getByRole('button',{name:'Send question',exact:true}).click();await expect(askDialog(page)).toBeVisible();await settlePanel(page);await expect(askDialog(page).getByRole('heading',{name:'Read the delivery roadmap'})).toBeVisible();
 await reference.getByRole('textbox',{name:'Ask HunpeoLabs'}).fill('How does pricing work?');await reference.getByRole('button',{name:'Send question',exact:true}).click();await expect(reference.getByRole('dialog')).toBeVisible();await expect.poll(()=>reference.getByRole('dialog').evaluate(e=>e.getAnimations().every(a=>a.playState!=='running'))).toBe(true);
 const panelShape=async(p:import('@playwright/test').Page)=>p.getByRole('dialog').evaluate(e=>{const r=e.getBoundingClientRect(),c=getComputedStyle(e),b=getComputedStyle(e,'::backdrop');return {width:r.width,height:r.height,radius:c.borderRadius,blur:b.backdropFilter,transition:b.transitionDuration};});expect(await panelShape(page)).toEqual(await panelShape(reference));
 await page.screenshot({path:'docs/evidence/ask-expanded-desktop.png',fullPage:true});await reference.screenshot({path:'docs/evidence/ask-source-expanded-desktop-fixture.png',fullPage:true});
 await askDialog(page).getByRole('button',{name:'Privacy',exact:true}).click();await expect(page.getByText(/Conversation stays in this page’s memory/)).toBeVisible();
 const panel=await askDialog(page).boundingBox();await page.mouse.move(panel!.x+100,panel!.y+40);await page.mouse.down();await page.mouse.move(5,5);await page.mouse.up();await expect(askDialog(page)).toBeVisible();await page.mouse.click(5,5);await expect(askDialog(page)).not.toBeVisible();await expect(askBox(page)).toBeFocused();
 await page.getByRole('button',{name:'Continue conversation'}).click();await expect(askDialog(page)).toBeVisible();await askDialog(page).getByRole('button',{name:'Open Roadmap',exact:true}).click();await expect(askDialog(page)).not.toBeVisible();await expect(page.getByRole('heading',{name:'Roadmap',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Hide Ask Workspace',exact:true}).click();const launcher=page.getByRole('button',{name:'Ask Workspace',exact:true});await expect(launcher).toBeEnabled();await expect(launcher).toBeFocused();await expect(launcher).toHaveAttribute('data-hint','true',{timeout:7000});const box=await launcher.boundingBox();expect(box!.width).toBe(56);expect(box!.height).toBe(56);await page.screenshot({path:'docs/evidence/ask-launcher-hint.png'});await launcher.click();await expect(askDialog(page)).toBeVisible();await page.keyboard.press('Escape');await expect(askDialog(page)).not.toBeVisible();
 await page.getByRole('button',{name:'Work',exact:true}).click();await page.getByRole('button',{name:'Create work item',exact:true}).click();await expect(page.getByRole('dialog',{name:'Create work item'})).toBeVisible();await expect(page.locator('[data-ask-workspace]')).not.toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'Create work item'})).not.toBeVisible();await page.getByRole('button',{name:'Ask Workspace',exact:true}).click();await expect(askDialog(page).getByRole('heading',{name:'Read the delivery roadmap'})).toBeVisible();
 await askBox(page).fill('Đọc lộ trình thế nào?');await page.getByRole('button',{name:'Send question',exact:true}).click();await expect(askDialog(page).getByRole('heading',{name:'Đọc lộ trình bàn giao'})).toBeVisible();await page.setViewportSize({width:390,height:844});await settlePanel(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const mobile=await askDialog(page).boundingBox();expect(mobile!.x).toBeGreaterThanOrEqual(0);expect(mobile!.y).toBeGreaterThanOrEqual(0);expect(mobile!.x+mobile!.width).toBeLessThanOrEqual(390);expect(mobile!.y+mobile!.height).toBeLessThanOrEqual(844);await expect(askDialog(page).getByRole('button',{name:'Quyền riêng tư',exact:true})).toBeInViewport();const privacyBounds=await askDialog(page).getByRole('button',{name:'Quyền riêng tư',exact:true}).boundingBox();expect(privacyBounds!.x+privacyBounds!.width).toBeLessThanOrEqual(mobile!.x+mobile!.width);await page.screenshot({path:'docs/evidence/ask-expanded-mobile-vi.png'});
 expect(unexpected).toEqual([]);await reference.close();
});

test('Actual Workspace Ask: project/account/reload isolation and observed membership revocation',async({page})=>{
 const ownerUser=await adminAuth.getUserByEmail('author@example.test');const principal=author(ownerUser.uid);
 await service.execute(principal,'bootstrap',{name:'Ask isolation project',repository:'https://github.com/example/ask-isolation',requestKey:key()});
 await loginAsk(page);await page.getByRole('combobox',{name:'Project',exact:true}).selectOption({label:'Customer Portal'});await expect(page.locator('[data-ask-workspace]')).toBeVisible();
 await askBox(page).fill('Private scope note for first project');await page.getByRole('button',{name:'Send question',exact:true}).click();await expect(askDialog(page).getByText('Private scope note for first project',{exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(askDialog(page)).not.toBeVisible();
 await page.getByRole('combobox',{name:'Project',exact:true}).selectOption({label:'Ask isolation project'});await expect(page.locator('[data-ask-workspace]')).toBeVisible();await expect(page.getByRole('button',{name:'Continue conversation'})).toHaveCount(0);await expect(page.getByText('Private scope note for first project',{exact:true})).toHaveCount(0);
 await askBox(page).fill('Private unsent draft');await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page.locator('[data-ask-workspace]')).toHaveCount(0);await loginAsk(page,'reviewer@example.test');await expect(askBox(page)).toHaveValue('');
 await askBox(page).fill('How do I read the roadmap?');await page.getByRole('button',{name:'Send question',exact:true}).click();await expect(askDialog(page)).toBeVisible();await page.reload();await expect(page.locator('[data-ask-workspace]')).toBeVisible();await expect(page.getByRole('button',{name:'Continue conversation'})).toHaveCount(0);await expect(askBox(page)).toHaveValue('');
 const reviewer=await adminAuth.getUserByEmail('reviewer@example.test');const projects=await service.execute(author(reviewer.uid),'list_projects',{});const project=projects.projects[0];const ref=db.doc(`workspaces/${project.workspaceId}/projects/${project.projectId}/members/${reviewer.uid}`);const before=(await ref.get()).data()!;
 try{await ref.update({active:false});await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.locator('[data-ask-workspace]')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Roadmap',exact:true})).toHaveCount(0);await expect(page.getByRole('alert')).toContainText(/access|unavailable/i);}finally{await ref.set(before);}
});

test('Isolated target adapter fixture: Stop, Retry, timeout, late answer and scope cancellation',async({page})=>{
 await page.goto('http://127.0.0.1:15174/target');await askBox(page).fill('Delayed first request');await page.getByRole('button',{name:'Send question',exact:true}).click();await expect(page.getByRole('button',{name:'Stop response',exact:true})).toBeVisible();await page.getByRole('button',{name:'Stop response',exact:true}).click();await expect(askDialog(page).getByText('Response stopped.',{exact:true})).toBeVisible();await page.evaluate(()=>{(window as any).fixtureAnswer();});await expect(askDialog(page).getByRole('heading',{name:'Read the delivery roadmap'})).toHaveCount(0);
 await askDialog(page).getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByRole('button',{name:'Stop response',exact:true})).toBeVisible();await page.evaluate(()=>{(window as any).fixtureFailure();});await expect(askDialog(page).getByRole('alert')).toContainText('Your question is still here');await expect(askBox(page)).toHaveValue('Delayed first request');
 await askDialog(page).getByRole('button',{name:'Try again',exact:true}).last().click();await expect(page.getByRole('button',{name:'Stop response',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(askDialog(page)).not.toBeVisible();await page.evaluate(()=>{(window as any).fixtureAnswer();});await page.getByRole('button',{name:'Continue conversation'}).click();await expect(askDialog(page).getByRole('heading',{name:'Read the delivery roadmap'})).toHaveCount(0);
 await askBox(page).fill('Delayed timeout');await page.getByRole('button',{name:'Send question',exact:true}).click();await expect(page.getByRole('button',{name:'Stop response',exact:true})).toBeVisible();await expect(askDialog(page).getByRole('region',{name:'Delayed timeout',exact:true}).getByRole('alert')).toContainText('Your question is still here',{timeout:18000});await page.evaluate(()=>{(window as any).fixtureAnswer();});await expect(askDialog(page).getByRole('heading',{name:'Read the delivery roadmap'})).toHaveCount(0);
 await page.keyboard.press('Escape');await expect(askDialog(page)).not.toBeVisible();await page.getByRole('button',{name:'Reset scope',exact:true}).click();await expect(page.getByRole('button',{name:'Continue conversation'})).toHaveCount(0);expect(await page.evaluate(()=>document.body.style.overflow)).toBe('');
});

test('Isolated target adapter fixture: IME, rapid motion reversal, reading position and reduced motion',async({page})=>{
 await page.goto('http://127.0.0.1:15174/target');await askBox(page).fill('roadmap');await askBox(page).evaluate(e=>e.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true,isComposing:true})));await expect(askDialog(page)).toHaveCount(0);await expect(askBox(page)).toHaveValue('roadmap');
 await page.getByRole('button',{name:'Send question',exact:true}).click();await expect(askDialog(page)).toBeVisible();await askDialog(page).getByRole('button',{name:'Close conversation',exact:true}).evaluate(e=>(e as HTMLButtonElement).click());await expect(askDialog(page)).not.toBeVisible();await expect(askBox(page)).toBeFocused();
 await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Continue conversation'}).click();await expect(askDialog(page)).toBeVisible();expect(await askDialog(page).evaluate(e=>e.getAnimations().filter(a=>a.playState==='running').length)).toBe(0);
 for(let i=0;i<7;i++){await askBox(page).fill(`roadmap ${i}`);await page.getByRole('button',{name:'Send question',exact:true}).click();await expect(askDialog(page).getByRole('heading',{name:'Read the delivery roadmap'})).toHaveCount(i+2);}
 await askBox(page).fill('Delayed reading');await page.getByRole('button',{name:'Send question',exact:true}).click();await expect(page.getByRole('button',{name:'Stop response',exact:true})).toBeVisible();const log=page.getByRole('log');await log.evaluate(e=>{e.scrollTop=80;e.dispatchEvent(new WheelEvent('wheel',{bubbles:true}));});await expect.poll(()=>log.evaluate(e=>e.scrollTop)).toBe(80);await page.evaluate(()=>{(window as any).fixtureAnswer();});await expect(askDialog(page).getByRole('heading',{name:'Read the delivery roadmap'})).toHaveCount(9);expect(await log.evaluate(e=>e.scrollTop)).toBe(80);
 await page.keyboard.press('Escape');await expect(askDialog(page)).not.toBeVisible();await page.getByRole('button',{name:'Hide Ask Workspace',exact:true}).click();await expect(page.getByRole('button',{name:'Ask Workspace',exact:true})).toBeEnabled();expect(await page.getByRole('button',{name:'Ask Workspace',exact:true}).evaluate(e=>getComputedStyle(e).animationName)).toBe('none');
});

test('Isolated target adapter fixture: accessibility tree, keyboard containment and 200 percent text scaling',async({page})=>{
 await page.goto('http://127.0.0.1:15174/target');await askBox(page).fill('roadmap');await page.getByRole('button',{name:'Send question',exact:true}).click();const dialog=askDialog(page);await expect(dialog).toBeVisible();await expect(dialog.getByRole('heading',{name:'Read the delivery roadmap'})).toBeVisible();
 const cdp=await page.context().newCDPSession(page);const tree=await cdp.send('Accessibility.getFullAXTree');const nodes=tree.nodes.filter((n:any)=>!n.ignored);expect(nodes.some((n:any)=>n.role?.value==='dialog'&&n.name?.value)).toBe(true);expect(nodes.some((n:any)=>n.role?.value==='log'&&n.properties?.some((p:any)=>p.name==='live'&&p.value?.value==='polite'))).toBe(true);await cdp.detach();
 for(let i=0;i<16;i++){await page.keyboard.press('Tab');expect(await dialog.evaluate(e=>e.contains(document.activeElement)||document.activeElement===document.body&&!document.hasFocus())).toBe(true);}
 await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});await page.setViewportSize({width:720,height:500});await expect(dialog).toBeVisible();await expect(dialog.getByRole('button',{name:'Privacy',exact:true})).toBeVisible();const bounds=await dialog.boundingBox();expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(721);await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(askBox(page)).toBeFocused();
});
