import {test} from 'node:test';import assert from 'node:assert/strict';
import {hash,bytesHash,canonical,validDate,schedule,calendarVariance,eligible,rank,throughput,onTime,assertAcyclic} from '../functions/src/domain/logic.js';
import type {Work} from '../functions/src/domain/model.js';
const work=(id:string,status='Ready'):Work=>({id,key:`HWS-${id}`,title:id,description:'',type:'task',priority:1,version:1,semanticVersion:1,status:status as Work['status'],ac:[{id:'AC-1',text:'persist'}],dependencies:[],parentId:null,assignee:null,start:null,end:null,contractId:'contract',archived:false,blocked:false,createdBy:'u',createdDate:0,changedBy:'u',changedDate:0,startedAt:null,completedAt:null,generation:0});
test('A08 date-only, DST/month bounds and +3 calendar days',()=>{assert.equal(calendarVariance('2027-01-18','2027-01-15'),3);assert.equal(calendarVariance('2026-03-09','2026-03-07'),2);assert.equal(calendarVariance('2026-11-02','2026-10-31'),2);assert.equal(validDate('2026-02-29'),false);assert.equal(validDate('2028-02-29'),true);assert.throws(()=>schedule('2026-05-02','2026-05-01'));});
test('A25 deterministic readiness excludes missing contract even at urgent priority',()=>{const a=work('a');a.priority=4;assert.deepEqual(eligible(a,false,true,true,false),['APPROVED_CONTRACT_REQUIRED']);assert.deepEqual(rank([work('b'),work('a')]).map(w=>w.id),['a','b']);assert.deepEqual(eligible(work('a'),true,true,true,false),[]);});
test('A09/A14 current throughput excludes cancelled/reopened; pending stays in denominator',()=>{const a=work('a','Done');a.completedAt=Date.parse('2027-01-15T12:00Z');const b=work('b');assert.equal(throughput([a,b,work('c','Cancelled')]),1);assert.deepEqual(onTime([a,b],{a:{end:'2027-01-15'},b:{end:'2027-01-15'}}),{numerator:1,denominator:2});assert.equal(onTime([a],{}),null);a.status='Ready';assert.equal(throughput([a,b]),0);});
test('A10 cycle/self/missing dependency rejected',()=>{assert.throws(()=>assertAcyclic([{id:'a',dependencies:['a']}]),/DEPENDENCY_CYCLE/);assert.throws(()=>assertAcyclic([{id:'a',dependencies:['b']}]),/FORBIDDEN/);assert.doesNotThrow(()=>assertAcyclic([{id:'a',dependencies:[]},{id:'b',dependencies:['a']}]));});
test('A64 deterministic canonical hash; actual UTF8 bytes differ when content changes',()=>{assert.equal(hash({b:2,a:1}),hash({a:1,b:2}));assert.equal(canonical({a:'Tiếng Việt'}),'{"a":"Tiếng Việt"}');assert.notEqual(bytesHash('a'),bytesHash('b'));});
