import {PlaneRoadmap} from '../features/roadmap/PlaneRoadmap';
import React,{useEffect,useState,useRef,lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import {onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,type User} from 'firebase/auth';
import {auth,command as requestCommand,key,runtimeMode} from '../lib/firebase/client';
import type {Project,Snapshot,Work,Document,WorkState,Recommendation} from '../domain/view';
import {Field,Badge,Empty} from '../components/Fields';
import '../styles/app.css';
const AskWorkspace=lazy(()=>import('../features/ask/AskWorkspace').then(m=>({default:m.AskWorkspace})));
const productName=import.meta.env.VITE_PRODUCT_NAME??'SatsunicPlan';
const nav=['Roadmap','Work','Knowledge','Ready work','Decisions','Reviews','Reports','Releases','Connect agent'] as const;
type Page=typeof nav[number];
const date=(n:number)=>new Date(n).toLocaleString('en-US');
function ProductMark(){return <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 6h10M9 12h10M5 18h10" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><circle cx="19" cy="6" r="1.5" fill="currentColor"/><circle cx="5" cy="12" r="1.5" fill="currentColor"/><circle cx="19" cy="18" r="1.5" fill="currentColor"/></svg>;}
const navIconPaths=[
 'M4 5h16M4 12h16M4 19h16M8 5v4M15 12v4',
 'M9 5h11M9 12h11M9 19h11M4 5h.01M4 12h.01M4 19h.01',
 'M12 5v15M3 4c4-1 6 0 9 2 3-2 5-3 9-2v15c-4-1-6 0-9 2-3-2-5-3-9-2V4Z',
 'm5 12 4 4L19 6',
 'm12 3 9 9-9 9-9-9 9-9Z',
 'M9 4h6v3H9V4ZM9 5H5v16h14V5h-4M8 14l3 3 5-6',
 'M4 20h16M7 16V9M12 16V4M17 16v-5',
 'M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5',
 'M14 3h7v7m0-7L10 14M10 5H4v15h15v-6',
];
function NavIcon({index}:{index:number}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={navIconPaths[index]}/></svg>;}
function accountLabel(user:User){return user.displayName?.trim()||user.email?.split('@')[0]?.replace(/[._-]+/g,' ').trim()||'Account';}
function SignOutIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M9 5H5v14h4M10 12h10m-4-4 4 4-4 4"/></svg>;}
function App(){
 const [user,setUser]=useState<User|null>(null),[authReady,setAuthReady]=useState(false);
 const [email,setEmail]=useState(runtimeMode==='emulator'?'author@example.test':''),[password,setPassword]=useState(runtimeMode==='emulator'?'Synthetic-only-2026!':'');
 const [projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState<Project|null>(null),[data,setData]=useState<Snapshot|null>(null);
 const [page,setPage]=useState<Page>('Roadmap'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [selected,setSelected]=useState<string|null>(new URLSearchParams(location.search).get('task'));
 const [state,setState]=useState<WorkState|null>(null),[tab,setTab]=useState('Overview');
 const [rec,setRec]=useState<Recommendation|null>(null),[showCreate,setShowCreate]=useState(false),[filter,setFilter]=useState('');
 const [doc,setDoc]=useState<Document|null>(null),[body,setBody]=useState(''),[docTitle,setDocTitle]=useState(''),[connection,setConnection]=useState<{secret:string;grantId:string}|null>(null);
 const [newName,setNewName]=useState(''),[repo,setRepo]=useState('https://github.com/example/customer-portal');
 useEffect(()=>{if(showCreate){const d=document.querySelector<HTMLDialogElement>('dialog.modal');if(d&&!d.open)d.showModal();}},[showCreate]);
 const documentEpoch=useRef(0);
 const [documentLoading,setDocumentLoading]=useState(false);
 const scopeEpoch=useRef(0),initialTask=useRef(new URLSearchParams(location.search).get('task')),initialAuth=useRef(true);
 function clearScope(){scopeEpoch.current++;documentEpoch.current++;setDocumentLoading(false);setSelected(null);setDoc(null);setBody('');setDocTitle('');setRec(null);setConnection(null);setState(null);setFilter('');setShowCreate(false);setNotice('');setError('');}
 async function command<T=Record<string,unknown>>(operation:string,input:unknown):Promise<T>{
  const epoch=scopeEpoch.current;
  try{return await requestCommand<T>(operation,input);}catch(e){
   if(epoch===scopeEpoch.current && ['This item is unavailable or you do not have access.','Sign in again to continue.'].includes((e as Error).message)){
    clearScope();setData(null);setProject(null);setProjects([]);setError('Project access is unavailable. Sign in again or choose an accessible project.');
   }
   throw e;
  }
 }
 useEffect(()=>onAuthStateChanged(auth,u=>{clearScope();if(initialAuth.current&&u)setSelected(initialTask.current);initialAuth.current=false;setUser(u);setAuthReady(true);setPage('Roadmap');setData(null);setProject(null);setProjects([]);setConnection(null);setState(null);}),[]);
 useEffect(()=>{if(user)void refreshProjects();},[user]);
 async function refreshProjects(){const epoch=scopeEpoch.current;try{const r=await command<{projects:Project[]}>('list_projects',{});if(epoch!==scopeEpoch.current)return;setProjects(r.projects);setProject(prev=>r.projects.find(p=>p.projectId===prev?.projectId)??r.projects[0]??null);}catch(e){if(epoch===scopeEpoch.current)setError((e as Error).message);}}
 const scope=project?{workspaceId:project.workspaceId,projectId:project.projectId}:null;
 async function refresh(){if(!scope)return;const epoch=scopeEpoch.current;const result=await command<Snapshot>('get_project_status',scope);if(epoch!==scopeEpoch.current)return;setData(result);if(selected){const r=await command<WorkState>('get_work_state',{...scope,taskId:selected});if(epoch===scopeEpoch.current)setState(r);}}
 useEffect(()=>{setData(null);if(scope)void refresh().catch(e=>setError(e.message));},[project?.projectId]);
 useEffect(()=>{let cancelled=false;if(scope&&selected)void command<WorkState>('get_work_state',{...scope,taskId:selected}).then(r=>{if(!cancelled)setState(r);}).catch(e=>setError(e.message));else setState(null);const u=new URL(location.href);if(selected)u.searchParams.set('task',selected);else u.searchParams.delete('task');history.replaceState(null,'',u);return()=>{cancelled=true;};},[selected,project?.projectId]);
 async function run(action:()=>Promise<unknown>,message='Changes saved'){const epoch=scopeEpoch.current;setBusy(true);setError('');setNotice('');try{await action();if(epoch!==scopeEpoch.current)return;setNotice(message);await refresh();}catch(e){if(epoch===scopeEpoch.current)setError((e as Error).message);}finally{setBusy(false);}}
 async function action(operation:string,input:Record<string,unknown>,message?:string){await run(()=>command(operation,{...scope,...input,requestKey:key()}),message);}
 function open(work:Work){setSelected(work.id);setTab('Overview');}
 const canReview=['admin','manager'].includes(data?.role??'');const canWrite=data?.role!=='viewer';
 const tasks=(data?.items??[]).filter(t=>!t.archived&&(!filter||`${t.title} ${t.key}`.toLowerCase().includes(filter.toLowerCase())));
 const task=data?.items.find(t=>t.id===selected);
 async function loadDoc(d:Document){const epoch=scopeEpoch.current,selection=++documentEpoch.current;setDoc(d);setDocTitle(d.title);setBody('');setDocumentLoading(true);try{const r=await command<{revision:{body:string}}>('get_document_revision',{...scope,documentId:d.id,revisionId:d.draftRevisionId});if(epoch!==scopeEpoch.current||selection!==documentEpoch.current)return;setBody(r.revision.body);}finally{if(epoch===scopeEpoch.current&&selection===documentEpoch.current)setDocumentLoading(false);}}
 if(!authReady)return <main className="login"><p role="status">Loading sign-in</p></main>;
 if(!user)return <main className="login"><div className="login-card"><span className="brand-mark" aria-hidden="true"><ProductMark/></span><h1>{productName}</h1><p>Keep requirements, execution and delivery evidence together.</p><form onSubmit={e=>{e.preventDefault();void run(()=>signInWithEmailAndPassword(auth,email,password),'Signed in');}}><Field label="Email"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></Field><Field label="Password"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></Field><button className="primary" disabled={busy}>Sign in</button><button type="button" disabled={busy} onClick={()=>void run(()=>createUserWithEmailAndPassword(auth,email,password),'Account created')}>Create account</button></form>{error&&<p role="alert" className="error">{error}</p>}</div></main>;
 if(!project)return <main className="onboarding"><h1>Create your project</h1><p>A project connects work, approved requirements and one repository.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{await command('bootstrap',{name:newName,repository:repo,requestKey:key()});await refreshProjects();},'Project created');}}><Field label="Project name"><input value={newName} onChange={e=>setNewName(e.target.value)} required/></Field><Field label="GitHub repository"><input value={repo} onChange={e=>setRepo(e.target.value)} required/></Field><button className="primary" disabled={busy}>Create project</button><button type="button" onClick={()=>void signOut(auth)}>Sign out</button></form>{error&&<p role="alert">{error}</p>}</main>;
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/" aria-label={productName}><span className="brand-mark" aria-hidden="true"><ProductMark/></span><span>{productName}<small>Project workspace</small></span></a><label className="project-select">Project<select value={project.projectId} onChange={e=>{const next=projects.find(p=>p.projectId===e.target.value);if(!next||next.projectId===project.projectId&&next.workspaceId===project.workspaceId)return;clearScope();setData(null);setProject(next);}}>{projects.map(p=><option key={p.projectId} value={p.projectId}>{p.name}</option>)}</select></label><nav aria-label="Project navigation">{nav.map((n,i)=><button key={n} aria-current={page===n?'page':undefined} onClick={()=>{setPage(n);setError('');}}><span aria-hidden="true"><NavIcon index={i}/></span>{n}</button>)}</nav><div className="sidebar-bottom"><div className="account-row"><span className="account-avatar" aria-hidden="true">{accountLabel(user).split(/\s+/).slice(0,2).map(part=>Array.from(part)[0]).join('').toUpperCase()}</span><span className="account-name" title={accountLabel(user)}>{accountLabel(user)}</span><button className="account-signout" aria-label="Sign out" title="Sign out" onClick={()=>void signOut(auth)}><SignOutIcon/></button></div><small className="product-credit">Product by HunpeoLabs</small></div></aside><main className="main"><header className="topbar"><span>{project.name} <span className="crumb">/</span> {page}</span><button disabled={busy} onClick={()=>void run(refresh,'Data refreshed')}>Refresh</button></header><div className="page-header"><div><h1>{page}</h1><p>{page==='Roadmap'?'Compare the commitment with the current plan and actual delivery.':page==='Ready work'?'Start work only when the required contract and context are approved.':page==='Reviews'?'Review the exact contract, submission and commit before accepting.':project.repository}</p></div>{page==='Work'&&canWrite&&<button className="primary" onClick={()=>setShowCreate(true)}>Create work item</button>}{page==='Roadmap'&&canReview&&<button onClick={()=>void action('publish_baseline',{reason:'Planning commitment published'},'Baseline published')}>Publish baseline</button>}</div><div className="status-area">{busy&&<p role="status">Saving changes</p>}{notice&&!busy&&<p role="status">{notice}</p>}{error&&<p role="alert" className="error">{error}</p>}</div>{!data?<p role="status">Loading project</p>:<>
 {!Object.values(data.coverage).every(Boolean)&&<p className="warning">This view contains a limited page. Reports are unavailable when work coverage is incomplete.</p>}
 {page==='Roadmap'&&<PlaneRoadmap key={`${project.workspaceId}/${project.projectId}`} tasks={tasks} baseline={data.baselines[0]} open={open}/>}
 {page==='Work'&&<><div className="toolbar"><Field label="Find in this page"><input type="search" value={filter} onChange={e=>setFilter(e.target.value)}/></Field><span>{tasks.length} visible items</span></div><div className="table-scroll"><table><thead><tr><th>Work item</th><th>Status</th><th>Planned dates</th><th>Contract</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td><button className="text-button" onClick={()=>open(t)}><small>{t.key}</small> {t.title}</button></td><td><Badge>{t.status}</Badge>{t.blocked&&<Badge>Blocked</Badge>}</td><td>{t.start??'Unscheduled'}{t.end&&` → ${t.end}`}</td><td>{t.contractId?'Pinned':'Missing'}</td></tr>)}</tbody></table></div>{!tasks.length&&<Empty>No work items in this view. Create an item to define its acceptance criteria.</Empty>}</>}
 {page==='Knowledge'&&<div className="knowledge"><section className="document-tree"><h2>Project documents</h2>{data.documents.map(d=><button key={d.id} aria-pressed={doc?.id===d.id} onClick={()=>void run(()=>loadDoc(d),'Document loaded')}>{d.title}<small>{d.revoked?'Revoked':d.approvedRevisionId?'Approved revision available':'Draft'}</small></button>)}<button onClick={()=>{documentEpoch.current++;setDocumentLoading(false);setDoc(null);setDocTitle('');setBody('');}}>New document</button></section><section className="editor"><h2>{doc?'Edit a new revision':'Create a document'}</h2><Field label="Title"><input value={docTitle} onChange={e=>setDocTitle(e.target.value)} required/></Field><Field label="Document content" hint="Plain text/Markdown. Saving creates a new immutable revision; it does not replace the approved content."><textarea rows={14} disabled={documentLoading} value={body} onChange={e=>setBody(e.target.value)}/></Field><div className="actions"><button className="primary" disabled={busy||!canWrite||!body||!docTitle} onClick={()=>void run(async()=>{await command('create_document',{...scope,...(doc?{documentId:doc.id}:{}),expectedVersion:doc?.version??0,title:docTitle,body,requestKey:key()});setDoc(null);},'Draft revision saved')}>Save new revision</button>{doc&&canReview&&<button disabled={busy} onClick={()=>void action('approve_document',{documentId:doc.id,revisionId:doc.draftRevisionId,expectedVersion:doc.version,decision:'approve'},'Revision approved')}>Approve draft revision</button>}</div>{doc&&<p className="hint">Draft: {doc.draftRevisionId}<br/>Approved: {doc.approvedRevisionId??'None'}. Another authorized person must approve.</p>}</section></div>}
 {page==='Ready work'&&<><div className="toolbar"><button className="primary" disabled={busy} onClick={()=>void run(async()=>{const epoch=scopeEpoch.current;const result=await command<Recommendation>('recommend_work',scope);if(epoch===scopeEpoch.current)setRec(result);},'Readiness checked')}>Check eligible work</button><p>Read-only check. This does not reserve work.</p></div>{rec&&<><h2>Eligible work</h2>{rec.suggested.map(t=><article className="work-row" key={t.taskId}><button className="text-button" onClick={()=>setSelected(t.taskId)}>{t.key} · {t.title}</button><Badge>Eligible · not reserved</Badge></article>)}{!rec.suggested.length&&<Empty>No eligible work in the evaluated page.</Empty>}<h2>Prerequisites to resolve</h2>{rec.blocked.map(t=><article className="work-row" key={t.taskId}><button className="text-button" onClick={()=>setSelected(t.taskId)}>{t.key} · {t.title}</button><span>{t.reasons.map(reasonLabel).join(' · ')}</span></article>)}{rec.truncated&&<p className="warning">Only the first 50 work items were evaluated.</p>}</>}</>}
 {page==='Decisions'&&<>{data.decisions.map(d=><article className="review-row" key={d.id}><h2>{d.question}</h2><Badge>{d.status}</Badge>{d.answer&&<p>{d.answer}</p>}{d.status==='Pending'&&canReview&&<form onSubmit={e=>{e.preventDefault();const text=new FormData(e.currentTarget).get('answer') as string;const t=data.items.find(t=>t.id===d.taskId);if(t)void action('decide_blocker',{taskId:t.id,expectedVersion:t.version,decisionId:d.id,answer:text,semanticChange:false},'Clarification recorded');}}><Field label="Non-semantic clarification" hint="Scope or business-rule changes require a new contract; they cannot be approved here."><textarea name="answer" required/></Field><button disabled={busy}>Record clarification</button></form>}</article>)}{!data.decisions.length&&<Empty>No decisions are waiting in this project.</Empty>}</>}
 {page==='Reviews'&&<>{data.submissions.map(s=>{const t=data.items.find(t=>t.id===s.taskId);return <article className="review-row" key={s.id}><header><button className="text-button" onClick={()=>setSelected(s.taskId)}>{t?.key??'Work item'} · {t?.title??'Open item'}</button><Badge>{({accept:'Accepted',request_changes:'Changes requested',reject:'Rejected',Pending:'Awaiting review'} as Record<string,string>)[s.review]??s.review}</Badge></header><dl><dt>Contract</dt><dd>{s.contractHash}</dd><dt>Commit</dt><dd>{s.headSha}</dd><dt>Evidence</dt><dd>Reported · provider verification {s.providerVerification==='NOT RUN'?'not run':s.providerVerification}</dd></dl><table><thead><tr><th>Criterion</th><th>Reported result</th><th>Command</th></tr></thead><tbody>{s.acEvidence.map(a=><tr key={a.acId}><td>{a.acId}</td><td>{a.result}</td><td>{a.command}</td></tr>)}</tbody></table><p>{s.limitations||'No limitations reported by the submitter.'}</p>{s.review==='Pending'&&canReview&&t&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action('review_delivery',{taskId:t.id,expectedVersion:t.version,submissionId:s.id,decision:f.get('decision'),reason:f.get('reason')},'Review decision recorded');}}><Field label="Review decision"><select name="decision"><option value="request_changes">Request changes</option><option value="accept">Accept delivery</option><option value="reject">Reject delivery</option></select></Field><Field label="Review reason"><textarea name="reason" required/></Field><button disabled={busy}>Record human review</button></form>}</article>;})}{!data.submissions.length&&<Empty>No delivery submissions yet. Submitted work will appear here for human review.</Empty>}</>}
 {page==='Reports'&&<><div className="metric-grid"><section><h2>Accepted throughput</h2><strong>{data.metrics?.throughput??'Unavailable'}</strong><p>Current non-archived Done items, counted once per item. Reopened and cancelled work is excluded.</p></section><section><h2>On-time commitment</h2><strong>{data.metrics?.onTime?`${data.metrics.onTime.numerator} / ${data.metrics.onTime.denominator}`:'N/A'}</strong><p>Completed on or before baseline end / baseline items with an end date. Incomplete items stay in the denominator. Current all-baseline cohort; calendar days in UTC.</p></section></div><p>As of {date(data.asOf)} · {data.baselines[0]?`Baseline ${data.baselines[0].id}`:'No baseline published'}.</p><h2>Drill-down</h2>{tasks.map(t=><article className="work-row" key={t.id}><button className="text-button" onClick={()=>open(t)}>{t.key} · {t.title}</button><Badge>{t.status}</Badge></article>)}<p className="hint">Historical reports, period filtering and additional KPI formulas are not implemented in this candidate.</p></>}
 {page==='Releases'&&<><h2>Deployment records</h2><p>These records describe manual observations. Recording an event does not deploy code.</p>{data.deployments.map(d=><article className="work-row" key={d.id}><span>{d.environment} · {d.reference}</span><Badge>{d.outcome} · manual</Badge><small>{date(d.createdDate)}</small></article>)}{!data.deployments.length&&<Empty>No deployment events recorded.</Empty>}{canReview&&<form className="compact-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action('record_deployment',{taskId:f.get('taskId'),guideRevisionId:f.get('guideRevisionId'),environment:f.get('environment'),outcome:f.get('outcome'),reference:f.get('reference')},'Manual deployment event recorded');}}><Field label="Accepted work item"><select name="taskId" required>{tasks.filter(t=>t.status==='Done').map(t=><option key={t.id} value={t.id}>{t.key} · {t.title}</option>)}</select></Field><Field label="Approved guide revision"><select name="guideRevisionId" required>{data.documents.filter(d=>d.approvedRevisionId&&!d.revoked).map(d=><option key={d.id} value={d.approvedRevisionId!}>{d.title}</option>)}</select></Field><Field label="Environment"><select name="environment"><option>test</option><option>staging</option><option>production</option></select></Field><Field label="Outcome"><select name="outcome"><option>succeeded</option><option>failed</option><option>rolled_back</option></select></Field><Field label="Artifact or release reference"><input name="reference" required/></Field><button disabled={busy||!tasks.some(t=>t.status==='Done')}>Record deployment event</button></form>}</>}
 {page==='Connect agent'&&(runtimeMode==='cloud'?<Empty>Agent connections are not available in this cloud workspace yet.</Empty>:<><section className="connection-intro"><h2>Delegate one project</h2><p>Your client receives approved project context. Content may leave your machine through the client or model provider you choose. Revoking access blocks future calls; it cannot recover content already transferred.</p><p>This local pilot uses dedicated bearer grants. Native OAuth and actual client compatibility remain unverified. Grants cannot approve requirements, accept delivery, publish baselines, change membership or deploy.</p></section>{canReview&&<form className="compact-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const epoch=scopeEpoch.current;const r=await command<{secret:string;grantId:string}>('grant_connection',{...scope,label:f.get('label'),write:f.get('write')==='on',consent:true,requestKey:key()});if(epoch===scopeEpoch.current)setConnection(r);},'Connection grant created');}}><Field label="Connection label"><input name="label" required placeholder="Local development client"/></Field><label className="check"><input type="checkbox" name="write"/>Allow claim, checkpoint and submission</label><label className="check"><input type="checkbox" required/>I authorize this project context to be transferred to my external client.</label><button className="primary" disabled={busy}>Create 24-hour grant</button></form>}{connection&&<section className="secret"><h2>Store this grant securely</h2><p>Shown once. Do not put it in your repository, screenshots or logs.</p><Field label="Access token"><input type="password" readOnly value={connection.secret}/></Field><button onClick={()=>{void navigator.clipboard.writeText(connection.secret).then(()=>setNotice('Token copied. Store it securely.')).catch(()=>setError('Copy did not complete.'));}}>Copy token</button><button onClick={()=>setConnection(null)}>Hide token</button><p>MCP endpoint: <code>http://127.0.0.1:15001/demo-hunpeolabs-workspace/us-central1/mcp</code></p><p>Use the client’s verified HTTP bearer-header configuration. Check connection with list tools and resolve_project; these are read-only.</p></section>}<h2>Your connections</h2>{data.connections.map(c=><article className="work-row" key={c.id}><span>{c.label}<small>{c.active?'Expires':'Revoked'} {date(c.expiresAt)}</small></span>{c.active&&<button disabled={busy} onClick={()=>{if(confirm('Revoke this connection? Future calls will be denied. Downloaded context remains outside this app.'))void action('revoke_connection',{grantId:c.id},'Connection revoked');}}>Revoke connection</button>}</article>)}{!data.connections.length&&<Empty>No connections created for this project.</Empty>}</>)}
 </>}{data&&<Suspense fallback={null}><AskWorkspace key={`${user.uid}/${project.workspaceId}/${project.projectId}`} suspended={showCreate} onNavigate={destination=>{setSelected(null);setPage(destination);setError('');}}/></Suspense>}</main>
 {selected&&task&&<aside className="inspector" aria-label="Work item details"><header><span>{task.key}</span><button onClick={()=>setSelected(null)}>Close details</button></header><h2>{task.title}</h2><Badge>{task.status}</Badge>{task.blocked&&<Badge>Blocked</Badge>}<div className="tabs" role="tablist" aria-label="Work details">{['Overview','Contract','Execution','Evidence'].map(n=><button key={n} role="tab" aria-selected={tab===n} onClick={()=>setTab(n)}>{n}</button>)}</div>{tab==='Overview'&&<><p>{task.description}</p><h3>Acceptance criteria</h3><ul>{task.ac.map(a=><li key={a.id}><strong>{a.id}</strong> · {a.text}</li>)}</ul><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action('edit_work',{taskId:task.id,expectedVersion:task.version,title:f.get('title'),start:f.get('start')||null,end:f.get('end')||null,archived:task.archived});}}><Field label="Title"><input name="title" defaultValue={task.title} key={task.version+'title'} required/></Field><Field label="Planned start"><input name="start" type="date" defaultValue={task.start??''} key={task.version+'start'}/></Field><Field label="Planned end"><input name="end" type="date" defaultValue={task.end??''} key={task.version+'end'}/></Field><button disabled={busy||!canWrite}>Save current plan</button></form><h3>Actual lifecycle</h3><p>Started: {task.startedAt?date(task.startedAt):'Not started'}<br/>Completed: {task.completedAt?date(task.completedAt):'Not completed'}</p></>}
 {tab==='Contract'&&<><h3>Pinned implementation contract</h3>{state?.contract?<><p>{state.contract.scope}</p><p>Non-goals: {state.contract.nonGoals||'None recorded'}</p><p className="hash">{state.contract.hash}</p><Badge>{state.contractApproval?.approved?'Approved':'Awaiting approval'}</Badge><h3>Exact document revisions</h3>{state.contract.documents.map(p=><p key={p.id} className="hash">{data?.documents.find(d=>d.id===p.id)?.title??p.id}<br/>{p.revisionId}</p>)}{canReview&&!state.contractApproval?.approved&&<button disabled={busy} onClick={()=>void action('approve_contract',{taskId:task.id,expectedVersion:task.version,contractId:state.contract!.id,decision:'approve'},'Contract approved')}>Approve pinned contract</button>}{state.claim&&<button disabled={busy||!canWrite} onClick={()=>void run(async()=>{const r=await command<{markdown:string;manifest:unknown}>('export_context',{...scope,taskId:task.id,executionId:state.claim!.executionId});download(`${task.key}-context.md`,r.markdown,'text/markdown');download(`${task.key}-manifest.json`,JSON.stringify(r.manifest,null,2),'application/json');},'Context files prepared')}>Export context fallback</button>}</>:<Empty>No implementation contract has been published.</Empty>}{canReview&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action('publish_contract',{taskId:task.id,expectedVersion:task.version,scope:f.get('scope'),nonGoals:f.get('nonGoals'),documentIds:f.getAll('documentIds')},'New contract published for approval');}}><Field label="Implementation scope"><textarea name="scope" required defaultValue={task.description}/></Field><Field label="Non-goals"><textarea name="nonGoals"/></Field><fieldset><legend>Required approved documents</legend>{data?.documents.filter(d=>d.approvedRevisionId&&!d.revoked).map(d=><label className="check" key={d.id}><input type="checkbox" name="documentIds" value={d.id}/>{d.title}</label>)}</fieldset><button disabled={busy}>Publish new contract</button></form>}</>}
 {tab==='Execution'&&<>{state?.claim?<><h3>Latest reservation</h3><Badge>{state.claim.state}</Badge><p>{state.leaseValid?'Lease valid until':'Lease expired at'} {date(state.claim.expiresAt)}</p><p>Reservation is separate from assignee and workflow. Expiry does not stop code edits on an external machine.</p><p className="hash">Execution {state.claim.executionId}<br/>Generation {state.claim.generation}</p></>:<Empty>No execution has reserved this item.</Empty>}<h3>Latest checkpoint</h3>{state?.checkpoint?<><p>{state.checkpoint.summary}</p><p>Next: {state.checkpoint.nextAction}</p><p className="hash">{state.checkpoint.headSha??'No shared commit reported'}</p><Badge>Reported · not provider verified</Badge></>:<Empty>No checkpoint submitted.</Empty>}<p>{state?.handoff==='HANDOFF_INCOMPLETE'?'Handoff incomplete: no shared commit checkpoint is available.':'Shared commit reported; a new client must verify it locally.'}</p>{state?.attempts.map(a=><p className="hash" key={a.executionId}>{a.state} · {a.executionId}</p>)}</>}
 {tab==='Evidence'&&<>{data?.submissions.filter(s=>s.taskId===task.id).map(s=><section key={s.id}><Badge>{({accept:'Accepted',request_changes:'Changes requested',reject:'Rejected',Pending:'Awaiting review'} as Record<string,string>)[s.review]??s.review}</Badge><p className="hash">{s.headSha}</p><p>Reported evidence · provider verification not run</p>{s.acEvidence.map(a=><p key={a.acId}>{a.acId} · {a.result} · {a.command}</p>)}</section>)}{!data?.submissions.some(s=>s.taskId===task.id)&&<Empty>No submission evidence yet.</Empty>}</>}
 </aside>}
 {showCreate&&<dialog aria-labelledby="create-title" className="modal" onCancel={()=>setShowCreate(false)}><header><h2 id="create-title">Create work item</h2><button onClick={()=>setShowCreate(false)}>Cancel</button></header><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const r=await command<{task:Work}>('create_work',{...scope,title:f.get('title'),description:f.get('description'),type:f.get('type'),priority:Number(f.get('priority')),ac:String(f.get('ac')).split('\n').filter(Boolean).map((text,i)=>({id:`AC-${i+1}`,text})),dependencies:[],parentId:null,assignee:null,start:f.get('start')||null,end:f.get('end')||null,requestKey:key()});setShowCreate(false);setSelected(r.task.id);},'Work item created');}}><Field label="Title"><input name="title" required maxLength={255} autoFocus/></Field><Field label="Description"><textarea name="description"/></Field><div className="form-grid"><Field label="Type"><select name="type"><option>task</option><option>story</option><option>bug</option><option>epic</option></select></Field><Field label="Priority"><select name="priority"><option value="2">Medium</option><option value="4">Urgent</option><option value="3">High</option><option value="1">Low</option><option value="0">None</option></select></Field><Field label="Planned start"><input name="start" type="date"/></Field><Field label="Planned end"><input name="end" type="date"/></Field></div><Field label="Acceptance criteria" hint="One criterion per line. IDs are assigned when saved."><textarea name="ac" required rows={4}/></Field><button className="primary" disabled={busy}>Create work item</button></form></dialog>}
 </div>;
}
function reasonLabel(code:string){return ({WORK_NOT_AVAILABLE:'Not available for implementation',AC_REQUIRED:'Acceptance criteria missing',APPROVED_CONTRACT_REQUIRED:'Approved contract required',CONTEXT_CHANGED:'Review changed context',DECISION_REQUIRED:'Decision pending',DEPENDENCY_NOT_ACCEPTED:'Dependency not accepted',CLAIM_CONFLICT:'Already reserved'} as Record<string,string>)[code]??'Prerequisite not met';}
function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
